<?php
/**
 * @Author
 * Roald Umandal.
 */

/**
 * Implements hook_menu().
 */
function coming_soon_menu() {

  $items['coming-soon'] = array(
    'title' => 'Coming Soon',
    'page callback' => 'coming_soon_page',
    'access arguments' => array('access coming soon'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements theme_preprocess_page().
 */
function coming_soon_preprocess_page(&$variables) {
  $arg = arg(0);
  if($arg == 'coming-soon') {
    $variables['theme_hook_suggestions'][] = 'coming_soon_page';
  }
}

/**
 * Coming soon page callback.
 */
function coming_soon_page() {
  // Init variables.
  $path = drupal_get_path('module', 'coming_soon');
  $header = array('type' => 'file', 'scope' => 'header', 'weight' => -18);
  $footer = array('type' => 'file', 'scope' => 'footer', 'weight' => -18);

  drupal_add_css($path . '/css/coming_soon.css', $header);
  drupal_add_js($path . '/js/coming_soon.js', $footer);

  $data = array(
    'title' => 'Hex',
  );

  return theme('coming_soon_page', array('items' => $data));
}


/**
 * Implement hook_theme().
 */
function coming_soon_theme() {
  return array(
    'coming_soon_page' => array(
      'variables' => array('items' => NULL),
      'template' => 'templates/coming-soon-page'
    ),
  );
}

/**
 * Implement hook_permission().
 */
function coming_soon_permission() {
  return array(
    'access coming soon' => array(
      'title' => t('Access coming soon page'),
      'description' => t('Allow viewing of coming soon page'),
    ),
  );
}